# Generated by Django 5.0.3 on 2024-05-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmHouseName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.accountmanagers')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityType', models.CharField(max_length=255)),
                ('ActivityName', models.CharField(max_length=255)),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='TypeObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=255)),
                ('IdActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectNumber', models.IntegerField(default=0)),
                ('ObjectPrize', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stato', models.CharField(choices=[('libera', 'libera'), ('prenotata', 'prenotata'), ('occupata', 'occupata'), ('non disponibile', 'non disponibile')], default='non disponibile', max_length=15)),
                ('IdTypeObjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.typeobjects')),
            ],
        ),
    ]
