# Generated by Django 5.0.3 on 2024-05-11 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('sconto', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('prize', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmHouseName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.accountmanagers')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True, verbose_name='data spesa')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.accountmanagers')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('codice_fiscale', models.CharField(default='', max_length=200)),
                ('iban', models.IntegerField(default=0)),
                ('mail', models.CharField(default='', max_length=200)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.accountmanagers')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True, verbose_name='data di entrata')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.accountmanagers')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='*', max_length=255)),
                ('mail', models.EmailField(default='', help_text='*', max_length=254)),
                ('number_cell', models.BigIntegerField(blank=True, help_text='inserisci numero di telefono. puoi non metterlo ', null=True)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.accountmanagers')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityType', models.CharField(max_length=255)),
                ('ActivityName', models.CharField(max_length=255)),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='GroupObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=255)),
                ('IdActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectNumber', models.IntegerField(default=0)),
                ('ObjectPrize', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stato', models.CharField(choices=[('libera', 'libera'), ('prenotata', 'prenotata'), ('occupata', 'occupata'), ('non disponibile', 'non disponibile')], default='non disponibile', max_length=15)),
                ('IdGroupObjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.groupobjects')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrOmData', models.DateField(auto_now_add=True, null=True, verbose_name='data di arrivo')),
                ('ToData', models.DateField(auto_now_add=True, null=True, verbose_name='data di partenza')),
                ('IdAccountManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.accountmanagers')),
                ('IdClient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione.clients')),
                ('IdFarmHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stipendio_ore', models.IntegerField(default=0)),
                ('giorni_lavorati', models.IntegerField(default=0)),
                ('ore_lavorate', models.IntegerField(default=0)),
                ('SalaryEmployee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione.employee')),
            ],
        ),
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_numbers', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
                ('IdAccountManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.accountmanagers')),
                ('IdClient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione.clients')),
                ('IdFarmHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.farmhouses')),
            ],
        ),
    ]
