# Generated by Django 5.0.3 on 2024-04-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='ClientRoom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.rooms'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='ClientServices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.services'),
        ),
    ]
