# Generated by Django 5.0.3 on 2024-04-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='ClientServices',
        ),
        migrations.AddField(
            model_name='clients',
            name='ClientServices',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestione.services'),
        ),
    ]
