# Generated by Django 5.0.3 on 2024-03-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0007_rename_date_clients_to'),
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicazione.clients'),
        ),
    ]
