# Generated by Django 5.0.3 on 2024-04-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_remove_clients_clientservices_clients_clientservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
