# Generated by Django 5.0.3 on 2024-04-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_rename_goout_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='ClientManager',
            new_name='IdAccountManagers',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeAccountManagers',
            new_name='IdAccountManagers',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='GoOutAccountManagers',
            new_name='IdAccountManagers',
        ),
        migrations.RenameField(
            model_name='farmhouses',
            old_name='FarmHousesAccountManagers',
            new_name='IdAccountManagers',
        ),
    ]
