# Generated by Django 5.0.3 on 2024-04-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_rename_clientmanager_clients_idaccountmanagers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='EarningsAccountManagers',
            new_name='IdAccountManagers',
        ),
    ]
