# Generated by Django 5.0.3 on 2024-04-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_rename_earningsaccountmanagers_earnings_idaccountmanagers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='ClientFarmHouse',
            new_name='IdFarmHouses',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeFarmHouses',
            new_name='IdFarmHouses',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='PromotionsFarmHouses',
            new_name='IdFarmHouses',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='RoomsFarmHouse',
            new_name='IdFarmHouses',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='ServicesFarmHouses',
            new_name='IdFarmHouses',
        ),
    ]
