# Generated by Django 5.0.3 on 2024-05-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('sconto', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('prize', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='*', max_length=255)),
                ('mail', models.EmailField(default='', help_text='*', max_length=254)),
                ('number_cell', models.BigIntegerField(blank=True, help_text='inserisci numero di telefono. puoi non metterlo ', null=True)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.accountmanagers')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True, verbose_name='data di entrata')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.accountmanagers')),
                ('IdActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.activity')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('codice_fiscale', models.CharField(default='', max_length=200)),
                ('iban', models.IntegerField(default=0)),
                ('mail', models.CharField(default='', max_length=200)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.accountmanagers')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.farmhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True, verbose_name='data spesa')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('IdAccountManagers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.accountmanagers')),
                ('IdActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.activity')),
                ('IdFarmHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.farmhouses')),
            ],
        ),
    ]
