# Generated by Django 5.0.3 on 2024-05-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_numbers', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrOmData', models.DateField(auto_now_add=True, null=True, verbose_name='data di arrivo')),
                ('ToData', models.DateField(auto_now_add=True, null=True, verbose_name='data di partenza')),
                ('IdActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.activity')),
                ('IdActivityObject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.activityobject')),
            ],
        ),
    ]
