# Generated by Django 5.0.3 on 2024-05-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_objects', '0001_initial'),
        ('principal_objects', '0001_initial'),
        ('register_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='IdClient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register_objects.clients'),
        ),
        migrations.AddField(
            model_name='visit',
            name='IdAccountManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.accountmanagers'),
        ),
        migrations.AddField(
            model_name='visit',
            name='IdClient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register_objects.clients'),
        ),
        migrations.AddField(
            model_name='visit',
            name='IdFarmHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_objects.farmhouses'),
        ),
    ]
