# Generated by Django 5.0.3 on 2024-03-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
                ('da', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('appunto', models.CharField(max_length=200)),
                ('cliente_occupante', models.CharField(max_length=200)),
            ],
        ),
    ]
