# Generated by Django 5.0.3 on 2024-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visit_numbers', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stipendio_ore', models.IntegerField(default=0)),
                ('stipendio_mese', models.IntegerField(default=0)),
                ('giorni_lavoro', models.IntegerField(default=0)),
                ('ore_lavorate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
                ('da', models.DateTimeField(verbose_name='data di arrivo')),
                ('to', models.DateTimeField(verbose_name='data di partenza')),
                ('stato', models.CharField(choices=[('L', 'libera'), ('O', 'occupata'), ('ND', 'non disponibile')], default='ND', max_length=10)),
                ('appunto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.IntegerField(default=0)),
                ('NumberOfUse', models.IntegerField(default=0)),
            ],
        ),
    ]
