# Generated by Django 5.0.3 on 2024-03-22 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0002_clients_employee_services_stipendio_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='da',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='to',
        ),
        migrations.AddField(
            model_name='clients',
            name='frOm_data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data di arrivo'),
        ),
        migrations.AddField(
            model_name='clients',
            name='frOm_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='mail',
            field=models.EmailField(default='', help_text='*', max_length=254),
        ),
        migrations.AddField(
            model_name='clients',
            name='numero_telefono',
            field=models.BigIntegerField(blank=True, help_text='inserisci numero di telefono. puoi non metterlo ', null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='to_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data di partenza'),
        ),
        migrations.AddField(
            model_name='clients',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='clienti_ospitabili',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(default='', help_text='*', max_length=255),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
